---
swagger: '2.0'
info:
  version: 0.0.1
  title: FlockIt
host: localhost:3000
basePath: "/"
schemes:
- http
- https
consumes:
- application/json
produces:
- application/json
paths:
  "$ref": "./paths/index.json"
definitions:
  "$ref": "./definitions/index.json"

